name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Show package-lock checksum
        run: |
          sha256sum package-lock.json

      - name: Debug environment
        run: |
          echo "Node version:"
          node -v

          echo "NPM version:"
          npm -v
          npm config get engine-strict
          cat package.json

          echo "Current commit:"
          git rev-parse HEAD

          echo "Checking package-lock contains @emnapi/core?"
          grep -n "@emnapi/core" package-lock.json || echo "@emnapi/core NOT FOUND"

      - name: Install dependencies
        run: npm ci --verbose

      - name: Run ESLint
        run: npm run lint

      - name: Check formatting
        run: npx prettier --check .
